aws:
  access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region:             <%= ENV['AWS_SQS_REGION'] %>
concurrency: 25  # The number of allocated threads to process messages. Default 25
queues:
  - [high_priority, 6]
  - [default, 2]
  - [low_priority, 1]
